name: adote_me
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    #Gerenciamento de Estado
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

    #Tradução para pt-Br de alguns componentes
  flutter_cupertino_localizations: ^1.0.1

    #Biblioteca para animação
  simple_animations: ^2.2.2

    #Biblioteca para alerta em widget
  rflutter_alert: ^1.0.3

    #Biblioteca para validar email
  email_validator: ^1.0.6

    #Biblioteca de tipos de carregamentos
  flutter_spinkit: ^4.1.2

    #Biblioteca de requisiçoes web
  http: ^0.12.2

    #Bibliotecas para Firebase
  firebase_core: ^0.7.0    #Recursos básicos
  firebase_auth: ^0.20.1   #autenticacao
  firebase_storage: ^7.0.0   #armazenamento arquivos
  cloud_firestore: ^0.16.0+1 #banco de dados
  google_sign_in: ^4.5.9      #login com google
  flutter_facebook_login: ^3.0.0 #login com facebook

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^1.1.2
  build_runner: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logoSmall.png
    - assets/images/dog.jpg
    - assets/images/bemVindo.png
    - assets/images/bemVindoTwo.png

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500
