name: adote_me
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    #Gerenciamento de Estado
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.3.1

    #Biblioteca para efeitos hover
  hovering: ^1.0.4

    #Tradução para pt-Br de alguns componentes
  flutter_cupertino_localizations: ^1.0.1

    #Biblioteca para animação
  simple_animations: ^3.1.1

    #Biblioteca para alerta em widget
  rflutter_alert: ^2.0.2

  #Biblioteca para validar email
  email_validator: ^2.0.1

    #Biblioteca de Icons
  flutter_vector_icons: ^1.0.0

    #Biblioteca de tipos de carregamentos
  flutter_spinkit: ^5.0.0

    #Biblioteca de Icons
  font_awesome_flutter: ^9.1.0

    #Biblioteca para dropdown
  custom_dropdown: ^0.0.2

    #Biblioteca para pegar fotos pela camera ou na galeria
  image_picker: ^0.8.2

    #Biblioteca para menu lateral tablet mobile
  hidden_drawer_menu: ^3.0.0

    #Biblioteca para responsividade
  responsive_builder: ^0.4.1

    #Biblioteca para fontes
  google_fonts: ^2.1.0

    #Biblioteca para formatos de input
  brasil_fields: ^1.1.3

    #Biblioteca para requisicao http
  dio: ^4.0.0

    #Biblioteca para carregamento de imagem
  cached_network_image: ^3.1.0

    #Bibliotecas para enviar para o wpp
  url_launcher: ^6.0.9
  whatsapp_unilink: ^2.0.0


    #Bibliotecas para Firebase
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logoSmall.png
    - assets/images/dog.jpg
    - assets/images/bemVindo.png
    - assets/images/bemVindoTwo.png

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500
